# Generated by Django 5.2 on 2025-07-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='exchanged',
            field=models.BooleanField(default=False, verbose_name='Обмен произведен'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='barter_app.ad', verbose_name='Интересующее объявление'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='barter_app.ad', verbose_name='Ваше объявление'),
        ),
    ]
