# Generated by Django 5.2 on 2025-07-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_app', '0002_ad_exchanged_alter_exchangeproposal_ad_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='URL изображения'),
        ),
    ]
